### PR TITLE
Always read alleles as strings (not bytes)

### LINKED ISSUE #810: Default SGkit alleles are byte strings, which confuses tsinfer:
If sd.sites_alleles[:] are byte strings, as occurs e.g. when using `sgkit.simulate_genotype_call_dataset()`, then when performing inference we get an error

```python
>>> print(sd.sites_alleles[:])
[[b'T' b'A']
 [b'C' b'T']
 [b'A' b'G']
 [b'C' b'G']
 [b'C' b'T']
 [b'G' b'C']
 [b'A' b'G']
 [b'T' b'A']]
```

```
tsinfer.infer(sd)

... 
 1886     derived_state[mutation_id] = site.reorder_alleles().index(allele)
   1887     mutation_id += 1
   1888 site_id += 1

ValueError: tuple.index(x): x not in tuple
```

Because `allele` here has been translated to a normal string, e.g. `"T"`, whereas the `site.reorder_alleles()` method returns a tuple of byte strings (`(b'C', b'T')`)

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #810. Waiting to activate test until I understand what's wrong in #927

### CODE REVIEW

**Comment by jeromekelleher** [comment]
So this doesn't help with #927 then?

**Comment by hyanwong** [comment]
No, #927 is independent of this PR, it's just that I noticed the problem when trying to write the unit tests.

**Comment by jeromekelleher** [comment]
I think you'd be better off doing a quick msprime->Zarr wrapper here until ``tskit2zarr`` exists, the sgkit simulator is pretty primitive. This code [here](https://github.com/sgkit-dev/sgkit/blob/27d77799d3e42a01ef263108f1cabcd33735986a/sgkit/tests/test_popgen.py#L63) should basically do it.

**Comment by hyanwong** [comment]
> This code [here](https://github.com/sgkit-dev/sgkit/blob/27d77799d3e42a01ef263108f1cabcd33735986a/sgkit/tests/test_popgen.py#L63) should basically do it.

Fab. Thanks Jerome. PR updated with this code. This is now for review (the actual change to formats.py is trivial: it's the test that takes most of the code)

**Review by benjeffery — APPROVED** [review]

**Comment by hyanwong** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
@mergifyio rebase

**Pull request merged**
