### PR TITLE
Remove pytest-xdist

### PR DESCRIPTION
**Pull request by benjeffery**
Investigating #771

### CODE REVIEW

**Comment by benjeffery** [comment]
Still fails with complete removal of `pytest-xdist`. Looking into the test.

**Comment by benjeffery** [comment]
Haha test passes when solely that test is run.

**Comment by jeromekelleher** [comment]
Maybe we should just disable those tests on Windows, probably not worth the effort in find out what's going on.

**Comment by benjeffery** [comment]
I've re-run this a successfully a few times.

**Review by jeromekelleher — APPROVED** [review]
Great, thanks for sorting this out.

**Pull request merged**
