### PR TITLE
Use a general function for checking np object array equality

### PR DESCRIPTION
**Pull request by hyanwong**
Simple test to be added in a moment. But I wanted to ask here: lots of these tests for equality go:

```
return (A and B and C and D)
```

where A, B, C, D are quite complicated. When these fail, it becomes really difficult to work out which of A, B, C, or D caused the failure. So I was wondering if we should switch to something like:

```
if not A:
    return False
if not B:
    return False
if not C:
    return False
if not D:
    return False
return True
```

What do you think @benjeffery ?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
The function here is a useful addition, so I'd say lets merge that first and think about other things later.

Just needs a handful of example tests, nothing elaborate.

**Comment by jeromekelleher** [comment]
Can you add a couple of unit tests here please @hyanwong? Really nothing elaborate, just checking the different size handling and an object array that should compare True and False.

**Comment by hyanwong** [comment]
Yep, sorry - just getting onto this! By the way, could you see if https://github.com/tskit-dev/tsinfer/pull/363 makes sense, then I can move forward with that too.

**Comment by hyanwong** [comment]
> Can you add a couple of unit tests here please @hyanwong? Really nothing elaborate, just checking the different size handling and an object array that should compare True and False.

I guess the most recent push should do it?

**Review by jeromekelleher — APPROVED** [review]

**Pull request merged**
