### PR TITLE
Sampledata subset/delete

### LINKED ISSUE #209: Create new samples file with a subset of sites
It's useful in a few instances to subset the sites in a SampleData file down to a limited number. Since we haven't got methods to iterate through e.g. the populations in a SampleData file, it's hard to recreate the file exactly (but with a subset of sites). We *can* do this, I think, by resizing the underlying zarr arrays, something like this:

```
def subset(sample_data, keep_sites_bool):
    site_shape = np.sum(keep_sites_bool).item(),
    subset = sample_data.copy()
    for attr in [a for a in dir(sample_data) if a.startswith('sites_')]:
        zarr_name = attr.replace('_', '/', 1)
        subset.data[zarr_name].resize(*(site_shape +  sample_data.data[zarr_name].shape[1:]))
        subset.data[zarr_name].set_basic_selection(..., sample_data.data[zarr_name][:][select])
    subset.finalise()
    return subset
```

Is this worth adding to tsinfer?

### PR DESCRIPTION
**Pull request by hyanwong**
To be considered after #254 is merged. Submitted here for initial review, fixes #209 and allows us to test inference against subsets of large datasets, such as 1000G (see comments at https://github.com/tskit-dev/tsinfer/issues/209#issuecomment-601259473). Rather than `SampleData.subset(sites=[], samples=[])`, I have reversed the logic and require the user to pass in sites or samples to *omit* from the new, returned SampleData file, rather than samples and sites to *keep*. This makes more sense with the default values of `None`, meaning do not remove any samples. I'm not sure about the name though. Do you have any better ideas than `delete`, @jeromekelleher ?

### CODE REVIEW

**Comment by hyanwong** [comment]
I've also started documenting parts of the SampleData API, as I had to refer to them when documenting the new function.

**Comment by hyanwong** [comment]
I think, pending a suggestion for name changes, this is ready for review and (hopefully) merge, @jeromekelleher ? Then I can code up the new inference tests on small fractions of larger datasets.

Perhaps @benjeffery has an idea for a nicer name that essentially means "make a copy of this data, but delete the following sites and/or samples from it"?

**Comment by benjeffery** [comment]
How about `copy_and_remove`? I liked `copy_except` but it seemed too cryptic.

**Comment by hyanwong** [comment]
@benjeffery I'm wondering if it's cleared to have something like: `subset(delete_samples, delete_sites)`. Or if we use `copy_and_remove`, I wonder if the current `copy` should be `copy_and_edit`?

**Comment by benjeffery** [comment]
I'd be happier with `subset` if the argument was the things you were keeping.

**Comment by jeromekelleher** [comment]
I think using ``subset()`` and stating the things you want to keep is the right way to go.

**Comment by jeromekelleher** [comment]
Can you pull the documentation stuff out of this PR please @hyanwong? It helps to have small, focused PRs when multiple people are working on the code. Should be easy enough to cherry pick off the last commit.

**Comment by hyanwong** [comment]
> Can you pull the documentation stuff out of this PR please @hyanwong? It helps to have small, focused PRs when multiple people are working on the code. Should be easy enough to cherry pick off the last commit.

Yep, no problem

**Comment by hyanwong** [comment]
Docs in another branch now. Just to check that we are happy with keeping `SampleData.copy()` with that name, as it is now being documented. The reason I ask is that it doesn't *quite* align with the normal semantics of "object.copy", as the created SampleData object is not exactly identical to the original, but instead opened in write-mode, needing to be `finalise`d before use. So I wondered if a clearer name might be e.g. `copy_and_edit()` or something similar?

**Comment by jeromekelleher** [comment]
Or maybe just `edit`, since it returns a file in edit mode? Let's not do that here though, one thing at a time.

**Comment by hyanwong** [comment]
> Or maybe just `edit`, since it returns a file in edit mode? Let's not do that here though, one thing at a time.

Sure. It's just if we want to call the function in this PR `copy_and_remove`, then it would argue for calling the other one `copy_and_edit`, I guess?

**Comment by hyanwong** [comment]
@jeromekelleher - as discussed, I tested without re-setting `sites_inference[:]`, and it seemed to work, but I before updating this PR I thought I should check that (a) there should be no problems with sites marked for inference at time 0 (which would be at the same time as samples, so perhaps weird) or sites marks for inference at time `np.nan` (if the freq is 0/0 because all sites have become missing). I'm wondering if it would be better to implement the "keep inference state as null" idea first, then all this goes away.

**Comment by jeromekelleher** [comment]
Yes, that does sounds like a good idea. I'll take a look at the ``sites_inference`` thing today.

**Comment by awohns** [comment]
A `subset` function seems like a really handy one to have, I'd certainly find it useful in a week or two with the big sampledata file I'm harmonizing now!

**Comment by awohns** [comment]
Just checking in on the status of this PR. Does it seem ok to merge? I've been using the delete function in my iterative script and it's been working fine.

**Comment by hyanwong** [comment]
I think the only thing remaining to discuss here is (a) the name of the function and (b) whether we should specify the sites/samples to *remove* or to *keep*.

**Comment by jeromekelleher** [comment]
We're still making semantic choices here, which #266 is removing. I've given a quick look through again, and I also don't understand a few things, so unless having this in master is blocking forward progress I don't want to get caught up in it right now.

**Comment by awohns** [comment]
No problem from my perspective leaving unmerged, working with @hyanwong 's branch installed has been fine for me

**Comment by hyanwong** [comment]
Replaced with #293

**Pull request closed without merging**
