### PR TITLE
Allow the same scheme name, if description matches

### LINKED ISSUE #929: Overwriting md schema
We've had problems in the past when taking tree seqs that are already inferred then trying to infer them again, because if the md schema name already exists, we bomb out, here:

https://github.com/tskit-dev/tsinfer/blob/1d45c0c8122d0680cee2fcfd4b23c7dbbcb7a497/tsinfer/inference.py#L118

I suggest that we add a description to the md schema field (e.g. for "sample_data_id", "sample_data_time" etc.) and if we detect that the description *also* matches in the existing metadata we then overwrite with a warning. The justification is that if the description matches (which presumably contains the word "tsinfer") then we are simply stomping on our own data.

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #929

### CODE REVIEW

**Comment by hyanwong** [comment]
Happy to use permissive_json, but don't we still want to warn if we are stomping on existing data. Having a defined schema is a nice way to do that.

**Comment by hyanwong** [comment]
Also, it's useful in tsdate because we are using short, non-intuitive names ("mn" and "vr") for the posterior means and variances, so documenting them is pretty useful IMO.

**Comment by jeromekelleher** [comment]
Sure, whatever is the shortest path here. Note that the schema is only one thing - if you want to truly check that you're not clobbering then you'd have to check the actual metadata items on the way in, because the existing schema may not declare all the fields.

**Review by jeromekelleher — APPROVED** [review]

**Comment by hyanwong** [comment]
Thanks. I think we should allow clobbering, but only if it's clear that the field was originally put in by tsinfer anyway. Checking the description is a reasonable way to do that (but actually, we should check the whole definition field, so I'll adjust this PR.). I think we warn when clobbering if the definition matches, but error out if the definition does not match.

**Review by benjeffery — APPROVED** [review]
I'm happy with throwing a warning in this case.

**Comment by hyanwong** [comment]
> I'm happy with throwing a warning in this case.

Great. Just made a minor change. Ready to review and hopefully merge @benjeffery ?

**Pull request merged**
