### PR TITLE
Get Python 3.9 working on CI

### PR DESCRIPTION
**Pull request by jeromekelleher**
... hopefully

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Woot, works!

**Comment by benjeffery** [comment]
WOW! How did you realise it was a compiler mis-match?!

**Review by benjeffery — APPROVED** [review]
LGTM! We should copy this across to the other repos too.

**Comment by jeromekelleher** [comment]
> WOW! How did you realise it was a compiler mis-match?!

Clang 12 was being a bit painful so I thought I'd factor that out first, and mixed compiler versions are a definite no-no on Windows. I'm not sure it even is the compiler, I think it's some other part of the low-level toolchain like the linker or something.

**Comment by jeromekelleher** [comment]
Merging manually as we're updating the github workflows.

**Comment by jeromekelleher** [comment]
> EDIT: Just seen the branch name. ￼

Snappy, eh?

**Comment by jeromekelleher** [comment]
What about the wheel builds, though?

**Comment by benjeffery** [comment]
Yep, they will need this too. Things like this is also why I'd like to run the test suite on the built wheels if it isn't too much work.

**Comment by jeromekelleher** [comment]
> Yep, they will need this too. Things like this is also why I'd like to run the test suite on the built wheels if it isn't too much work.

Hmm, I'm a bit nervous about mixing compilers for the shipped wheels. We should be building these without using conda, but using  "native" compiler. I'll take a look.

**Comment by jeromekelleher** [comment]
No, there's no conda in the wheel building so we're all good. No need to change things I think.

**Comment by benjeffery** [comment]
> No, there's no conda in the wheel building so we're all good. No need to change things I think.

Phew! Sorry, I assumed I'd had to resort to that.

**Pull request merged**
