### PR TITLE
Add provenance output for CLI

### LINKED ISSUE #730: Add CLI args to provenance
This circumvents all the difficult decisions about what should and should not be stored as provenance. I'll make a PR.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Closes #730

Example:
```
jk@tempest$ python3 -m tsinfer ms -v tmp.samples                                                                                                                                              
2022-10-11 16:58:01,821 [66212] INFO     tsinfer.formats: Loaded SampleData(num_samples=5, num_sites=6)                                                                                       
2022-10-11 16:58:01,821 [66212] INFO     tsinfer.cli: Loading ancestral genealogies from tmp.ancestors.trees                                                                                  
2022-10-11 16:58:01,822 [66212] INFO     tsinfer.inference: Mismatch prevented by setting constant high recombination and low mismatch probabilities                                          
2022-10-11 16:58:01,822 [66212] INFO     tsinfer.inference: Summary of recombination probabilities between sites: min=0.01; max=0.01; median=0.01; mean=0.01                                  
2022-10-11 16:58:01,822 [66212] INFO     tsinfer.inference: Summary of mismatch probabilities over sites: min=1e-20; max=1e-20; median=1e-20; mean=1e-20                                      
2022-10-11 16:58:01,822 [66212] INFO     tsinfer.inference: Matching using 13 digits of precision in likelihood calcs                                                                         
2022-10-11 16:58:01,823 [66212] INFO     tsinfer.inference: Loaded 5 samples 4 nodes; 3 edges; 4 sites; 4 mutations                                                                           
2022-10-11 16:58:01,824 [66212] INFO     tsinfer.inference: Started matching for 5 samples    
2022-10-11 16:58:01,824 [66212] INFO     tsinfer.inference: Inserting sample paths: 5 edges in total
2022-10-11 16:58:01,824 [66212] INFO     tsinfer.inference: Finalising tree sequence          
2022-10-11 16:58:01,828 [66212] INFO     tsinfer.inference: Built samples tree sequence: 9 nodes (0 pc); 8 edges; 4 sites; 4 mutations
2022-10-11 16:58:01,829 [66212] INFO     tsinfer.inference: Mapping additional sites          
2022-10-11 16:58:01,830 [66212] INFO     tsinfer.inference: Removing the oldest edge to detach the virtual-root-like ancestor
2022-10-11 16:58:01,830 [66212] INFO     tsinfer.inference: Splitting the all zeros grand MRCA into separate nodes
2022-10-11 16:58:01,830 [66212] INFO     tsinfer.inference: Removing topology in flanking regions with keep_intervals
2022-10-11 16:58:01,831 [66212] INFO     tsinfer.inference: Simplifying with filter_sites=False, filter_populations=False, filter_individuals=False, and keep_unary=True on 9 nodes and 7 edge
s                                                                                             
2022-10-11 16:58:01,831 [66212] INFO     tsinfer.inference: Finished simplify; now have 8 nodes and 7 edges
2022-10-11 16:58:01,831 [66212] INFO     tsinfer.cli: Writing output tree sequence to tmp.trees
2022-10-11 16:58:01,832 [66212] INFO     tsinfer.cli: wall time = a moment                    
2022-10-11 16:58:01,832 [66212] INFO     tsinfer.cli: rusage: user=a moment; sys=0.10s; max memory=54.6 MiB
jk@tempest$ tskit provenances tmp.trees | cut -f 3 | tail -n1 | jq . 
{
  "schema_version": "1.0.0",
  "software": {
    "name": "tsinfer",
    "version": "0.2.4.dev28+gd9cbe71"
  },
  "parameters": {
    "args": [
      "ms",
      "-v",
      "tmp.samples"                            
    ],                                         
    "command": "/home/jk/work/github/tsinfer/tsinfer/__main__.py"                              
  },                                           
  "environment": {                             
    "libraries": {                             
      "zarr": {                                
        "version": "2.10.3"
      },                                       
      "numcodecs": {                           
        "version": "0.9.1"
      },                                       
      "lmdb": {                                
        "version": "0.98"
      },                                       
      "tskit": {                               
        "version": "0.5.3"
      }                                        
    },                                         
    "os": {                                    
      "system": "Linux",
      "node": "tempest",
      "release": "5.4.0-126-generic",
      "version": "#142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022",                               
      "machine": "x86_64"
    },                                         
    "python": {                                
      "implementation": "CPython",
      "version": [                             
        "3",                                   
        "8",                                   
        "10"                                   
      ]                                        
    }                                          
  }                                            
}                                              
```

### CODE REVIEW

**Comment by hyanwong** [comment]
This LGTM. If we merge I can get #435 fixed

**Review by benjeffery — APPROVED** [review]
Looks fine, but I note that this isn't what `msprime` does for `cli` commands - it encodes the arguments in python-kwarg style.

**Comment by hyanwong** [comment]
Actually, I'm having problems here @jeromekelleher. For a start, when I run an inference in the CLI via the test suite, I get a weird command appended: `"args": [], "command": "-c"`:

```
Provenance(id=0, timestamp='2022-10-13T13:53:15.833472', record='{"environment": {"libraries": {"lmdb": {"version": "1.2.1"}, "numcodecs": {"version": "0.7.3"}, "tskit": {"version": "0.5.3"}, "zarr": {"version": "2.8.3"}}, "os": {"machine": "x86_64", "node": "Yans-New-Air", "release": "20.6.0", "system": "Darwin", "version": "Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64"}, "python": {"implementation": "CPython", "version": ["3", "9", "4"]}}, "parameters": {"command": "generate-ancestors"}, "schema_version": "1.0.0", "software": {"name": "tsinfer", "version": "0.2.4.dev57+gda12dbd.d20221013"}}')
Provenance(id=1, timestamp='2022-10-13T13:53:15.854397', record='{"schema_version": "1.0.0", "software": {"name": "tsinfer", "version": "0.2.4.dev57+gda12dbd.d20221013"}, "parameters": {"source": {"uuid": "98cc63ff-7df1-44d7-ac5f-a00058f3ae43"}, "command": "match_ancestors"}, "environment": {"libraries": {"zarr": {"version": "2.8.3"}, "numcodecs": {"version": "0.7.3"}, "lmdb": {"version": "1.2.1"}, "tskit": {"version": "0.5.3"}}, "os": {"system": "Darwin", "node": "Yans-New-Air", "release": "20.6.0", "version": "Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64", "machine": "x86_64"}, "python": {"implementation": "CPython", "version": ["3", "9", "4"]}}}')
Provenance(id=2, timestamp='2022-10-13T13:53:15.855013', record='{"schema_version": "1.0.0", "software": {"name": "tsinfer", "version": "0.2.4.dev57+gda12dbd.d20221013"}, "parameters": {"args": [], "command": "-c"}, "environment": {"libraries": {"zarr": {"version": "2.8.3"}, "numcodecs": {"version": "0.7.3"}, "lmdb": {"version": "1.2.1"}, "tskit": {"version": "0.5.3"}}, "os": {"system": "Darwin", "node": "Yans-New-Air", "release": "20.6.0", "version": "Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64", "machine": "x86_64"}, "python": {"implementation": "CPython", "version": ["3", "9", "4"]}}}')
Provenance(id=3, timestamp='2022-10-13T13:53:15.872655', record='{"schema_version": "1.0.0", "software": {"name": "tsinfer", "version": "0.2.4.dev57+gda12dbd.d20221013"}, "parameters": {"command": "match-samples"}, "environment": {"libraries": {"zarr": {"version": "2.8.3"}, "numcodecs": {"version": "0.7.3"}, "lmdb": {"version": "1.2.1"}, "tskit": {"version": "0.5.3"}}, "os": {"system": "Darwin", "node": "Yans-New-Air", "release": "20.6.0", "version": "Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64", "machine": "x86_64"}, "python": {"implementation": "CPython", "version": ["3", "9", "4"]}}}')
Provenance(id=4, timestamp='2022-10-13T13:53:15.879025', record='{"schema_version": "1.0.0", "software": {"name": "tsinfer", "version": "0.2.4.dev57+gda12dbd.d20221013"}, "parameters": {"args": [], "command": "-c"}, "environment": {"libraries": {"zarr": {"version": "2.8.3"}, "numcodecs": {"version": "0.7.3"}, "lmdb": {"version": "1.2.1"}, "tskit": {"version": "0.5.3"}}, "os": {"system": "Darwin", "node": "Yans-New-Air", "release": "20.6.0", "version": "Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64", "machine": "x86_64"}, "python": {"implementation": "CPython", "version": ["3", "9", "4"]}}}')
```

And even more strangely, even if I run the straight `tsinfer infer` command (rather than ga+ma+ms), I still get the separate processes stored in the provenances, so I can't test whether or not the parameters passed to the `infer` command have come through correctly. Any idea what's going on?

**Comment by hyanwong** [comment]
> even more strangely, even if I run the straight `tsinfer infer` command (rather than ga+ma+ms), I still get the separate processes stored in the provenances, so I can't test whether or not the parameters passed to the `infer` command have come through correctly. Any idea what's going on?

Ah, perhaps I'm looking at the provenances that get stored because we do that when we call `generate_ancestors`, `match_ancestors` ... etc within python. Should we have an (undocumented) flag to e.g. generate_ancestors that says not to store the provenance?

**Comment by hyanwong** [comment]
Ah, this is what https://github.com/tskit-dev/tsinfer/pull/558 does! I forgot I did that. I vote for merging that PR (all it does is make the provenance recording consistently with what happens in tskit).

**Comment by jeromekelleher** [comment]
You can't inspect these provenance values from the test suite @hyanwong, as you get the value of sys.argv from the call to pytest and not what you'd expect. I didn't think it was worth the effort of working around this.

**Comment by hyanwong** [comment]
Ah yes, thanks. I see the comment in there now. I guess there's no way of testing in the suite whether or not e.g. mismatch was called properly then.

**Comment by jeromekelleher** [comment]
As a general rule for this sort of thing I guess one would mock out key functions, and check that they were called with the expected parameters.

**Pull request merged**
