### PR TITLE
Add docstring for SampleData.sequence_length

### LINKED ISSUE #691: SampleData attribute sequence_length
There is an argument to specify `sequence_length` when instantiating a `SampleData` object, but I'm not seeing a convenient way to get the `sequence_length` property from an existing `SampleData` object, at least not in the online API documentation. Should it be added? Or is it not there for some reason?

### PR DESCRIPTION
**Pull request by szhan**
Fixes #691

### CODE REVIEW

**Comment by szhan** [comment]
@mergifyio rebase

**Review by hyanwong — APPROVED** [review]
LGTM, although the convention in the rest of the file seems to be to put the docstring on a new line

```
"""
Like so
"""
```

**Comment by benjeffery** [comment]
Your CI is faliing here as this PR isn't rebased to `main`
If you look at https://github.com/tskit-dev/tsinfer/network you can see your branch coming from the past.
Screenshot from 2022-07-07 12-25-54

**Comment by benjeffery** [comment]
Happy to hop on a call, but it should be as easy as `git rebase main`.

**Review by benjeffery — APPROVED** [review]
LGTM!

**Pull request merged**
