### PR TITLE
Add ancestral length scatterplot

### PR DESCRIPTION
**Pull request by hyanwong**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good @hyanwong, but the gitting has gone slightly funny. You need to rebase and squash the commits:
```
git fetch upstream
git rebase -i upstream master # See below for help with squashing here
git push -f origin  add-ancestral-length-scatterplot
```
Squash the commits down to one. See http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html for help with squashing.

Don't merge upstream changes into your local repo, it's much simpler to checkout a new branch and rebase off upstream/master.

**Comment by hyanwong** [comment]
I did try to do this, but when I do

`git rebase -i upstream master`

I got 

```
Yans-MacBook-Air:tsinfer yan$ git rebase -i upstream master
fatal: Needed a single revision
invalid upstream 'upstream'
```

And I assumed (wrongly) that you meant to type `git rebase -i upstream/master` which I did.

God, I hate this git complication. Why does it have to be so difficult.

**Comment by jeromekelleher** [comment]
I fixed it there and pushed to your branch. Sorry, I should have typed ``git rebase -i upstream/master``, but otherwise everything was fine.

Distributed revision control is a hard and complicated problem and git is a hard and complicated tool. If you follow the recipe I gave earlier (making sure you always ``git fetch upstream`` before you start) then it'll work fine 90% of the time.

**Comment by hyanwong** [comment]
Thanks for sorting. Weirdly, I did exactly that. Here's what I did:

```
Yans-MacBook-Air:tsinfer yan$ git fetch upstream
Yans-MacBook-Air:tsinfer yan$ git rebase -i upstream/master
Successfully rebased and updated refs/heads/add-ancestral-length-scatterplot.
Yans-MacBook-Air:tsinfer yan$ git push origin add-ancestral-length-scatterplot
To https://github.com/hyanwong/tsinfer.git
 ! [rejected]        add-ancestral-length-scatterplot -> add-ancestral-length-scatterplot (non-fast-forward)
error: failed to push some refs to 'https://github.com/hyanwong/tsinfer.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Yans-MacBook-Air:tsinfer yan$ git pull
Merge made by the 'recursive' strategy.
Yans-MacBook-Air:tsinfer yan$ git push origin add-ancestral-length-scatterplot
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.11 KiB | 1.11 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/hyanwong/tsinfer.git
   d917d36..44cc290  add-ancestral-length-scatterplot -> add-ancestral-length-scatterplot
```

**Comment by hyanwong** [comment]
So do I need to do anything else to this branch? It sounds like you have fixed it up and all is ready to go.

**Comment by jeromekelleher** [comment]
Nope, we're all done here.

You missed the all important ``-f``  from git push! This is a force push: rebasing is a nasty thing to do because it rewrites history, which can cause confusion (like you experienced above). I don't have a very deep understanding of all this, I just have a recipe that works most of the time...

**Comment by hyanwong** [comment]
Thanks, will keep this thread as a ref to remember `-f`. I do find myself getting into knots more often than I would hope with Git. But as you say, it's not a trivial problem that it's trying to solve.

**Pull request merged**
