### PR TITLE
GitHub actions tests

### PR DESCRIPTION
**Pull request by benjeffery**
Move tests to github actions

### CODE REVIEW

**Comment by benjeffery** [comment]
@hyanwong we have seg fault on OSX with python 3.9 - can you reproduce?

**Comment by hyanwong** [comment]
> @hyanwong we have seg fault on OSX with python 3.9 - can you reproduce?

Haven't got 3.9 installed. Hang on and I'll check.

**Comment by jeromekelleher** [comment]
> @hyanwong we have seg fault on OSX with python 3.9 - can you reproduce?

We should probably file this as an issue and disable the tests for now - best to get this merged ASAP

I've turned off test builds on Appveyor, so this should build OK next time you push. It's probably time to look at uninstalling the Appveyor app from GitHub too, I think we're happy with how Actions are doing on Windows?

**Comment by hyanwong** [comment]
Yep. Segfault. Not on 3.8 though. Here's a clip of the output from 3.9:

```
/local/anaconda3/envs/python39/lib/python3.9/site-packages/execnet/gateway_base.py", line 220 in run
  File "/usr/local/anaconda3/envs/python39/lib/python3.9/site-packages/execnet/gateway_base.py", line 285 in _perform_spawn
  File "/usr/local/anaconda3/envs/python39/lib/python3.9/site-packages/execnet/gateway_base.py", line 267 in integrate_as_primary_thread
  File "/usr/local/anaconda3/envs/python39/lib/python3.9/site-packages/execnet/gateway_base.py", line 1060 in serve
  File "/usr/local/anaconda3/envs/python39/lib/python3.9/site-packages/execnet/gateway_base.py", line 1554 in serve
  File "<string>", line 8 in <module>
  File "<string>", line 1 in <module>
gw0 [598] / gw4 C / gw2 [598] / gw3 [598]    [gw2] node down: Not properly terminated

```

**Comment by jeromekelleher** [comment]
Good stuff, thanks @hyanwong. Can you open an issue with the problem, and see if you can track down which test is segfaulting? ``python3 -m pytest -vs -n0 `` is good for this (runs tests sequentially verbosely)

**Comment by benjeffery** [comment]
The actions log has this as I ran with those options:
```
============================= test session starts ==============================
platform darwin -- Python 3.9.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /usr/local/miniconda/envs/anaconda-client-env/bin/python
cachedir: .pytest_cache
rootdir: /Users/runner/work/tsinfer/tsinfer, configfile: pytest.ini, testpaths: tests
plugins: xdist-2.1.0, forked-1.3.0
collecting ... collected 598 items

tests/test_cli.py::TestMain::test_cli_main PASSED                        [  0%]
tests/test_cli.py::TestMain::test_main PASSED                            [  0%]
tests/test_cli.py::TestDefaultPaths::test_get_default_path PASSED        [  0%]
tests/test_cli.py::TestDefaultPaths::test_get_ancestors_path PASSED      [  0%]
tests/test_cli.py::TestDefaultPaths::test_get_ancestors_trees_path PASSED [  0%]
tests/test_cli.py::TestDefaultPaths::test_get_output_trees_path PASSED   [  1%]
Fatal Python error: Segmentation fault

Current thread 0x00000001172a4dc0 (most recent call first):
  File "/Users/runner/work/tsinfer/tsinfer/tsinfer/inference.py", line 1092 in __complete_epoch
  File "/Users/runner/work/tsinfer/tsinfer/tsinfer/inference.py", line 1119 in __match_ancestors_single_threaded
  File "/Users/runner/work/tsinfer/tsinfer/tsinfer/inference.py", line 1166 in match_ancestors
  File "/Users/runner/work/tsinfer/tsinfer/tsinfer/inference.py", line 367 in match_ancestors
  File "/Users/runner/work/tsinfer/tsinfer/tests/test_cli.py", line 132 in setUp
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/unittest/case.py", line 547 in _callSetUp
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/unittest/case.py", line 589 in run
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/unittest/case.py", line 653 in __call__
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/unittest.py", line 278 in runtest
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/runner.py", line 163 in pytest_runtest_call
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/runner.py", line 256 in <lambda>
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/runner.py", line 310 in from_call
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/runner.py", line 255 in call_runtest_hook
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/runner.py", line 216 in call_and_report
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/runner.py", line 127 in runtestprotocol
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/runner.py", line 110 in pytest_runtest_protocol
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/main.py", line 338 in pytest_runtestloop
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/main.py", line 313 in _main
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/main.py", line 257 in wrap_session
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/main.py", line 306 in pytest_cmdline_main
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/site-packages/pytest/__main__.py", line 5 in <module>
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/local/miniconda/envs/anaconda-client-env/lib/python3.9/runpy.py", line 197 in _run_module_as_main
/Users/runner/work/_temp/7730ec96-18ae-4cac-99b8-f1600a882b39.sh: line 3:  2007 Segmentation fault: 11  python -m pytest -xv -n0
tests/test_cli.py::TestCommandsDefaults::test_augment_ancestors 
Error: Process completed with exit code 139.
```

**Comment by benjeffery** [comment]
Ready to merge - note that this removes the clang-format check. This is will be added back in with the next PR as an update to the pre-commit config.

**Comment by benjeffery** [comment]
I'll merge this now.
@jeromekelleher Yeah, I think you can disable AppVeyor. Sad after so many "fun" times together, but hey ho.

**Pull request merged**
