### PR TITLE
Python 3.11 support

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]

**Comment by benjeffery** [comment]
Mamba gives a _much_ better error:
```
Encountered problems while solving:
  - package numcodecs-0.10.0-py39h5a03fae_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
  ```

**Comment by jeromekelleher** [comment]
Ahhh. Wonder what's going on with numcodecs? They're usually pretty good for this.

**Comment by benjeffery** [comment]
https://anaconda.org/conda-forge/numcodecs/files seems to show a py3.11 package.

**Comment by jeromekelleher** [comment]
Let's just let this one sit for a bit - 3.11 packages aren't crucial for tsinfer here, right?

**Comment by benjeffery** [comment]
Superseded by #936

**Pull request closed without merging**
