### PR TITLE
Document inherited methods in SampleData

### PR DESCRIPTION
**Pull request by benjeffery**
@hyanwong Here's the option in sphinx to document inherited members.

### CODE REVIEW

**Comment by hyanwong** [comment]
Cool, thanks!

**Comment by hyanwong** [comment]
(Needed this for tsinfer, not tksit, but I can make the change there)

**Comment by benjeffery** [comment]
I thought this was tsinfer?

**Comment by hyanwong** [comment]
Oops. dunno how I mistook this for tskit. Sorry. Brain fart.

Actually, it's because the header says "merge 1 commit into tskit-dev:master from ...", and doesn't list the actual project within tskit-dev.

**Comment by hyanwong** [comment]
@jeromekelleher I'm trying to document `SampleData.copy()` and friends (marked as a TODO, and relevant to #209 . This PR does that, but the docs for SampleData then end up referring to DataContainer (which isn't documented), e.g. under the SampleData API docs we have:

image

Is that OK, or if not, how and where do you want to write the docstrings? it would be nice if we could programmatically refer to the child class name itself in the docstring, but I can't see any option to do that in Sphinx.

**Comment by hyanwong** [comment]
NB:  I guess we could work around it by changing the language, e.g. using the word "class" rather than "DataContainer" where necessary.

**Comment by jeromekelleher** [comment]
Looks good to me, thanks @benjeffery.

**Pull request merged**
