### PR TITLE
Use dependency levels rather than epochs

### PR DESCRIPTION
**Pull request by hyanwong**
OMG @jeromekelleher . I think this might actually work to address #147 . It's only failing on 3 tests, all of them when doing `self.tree_sequence_builder.add_path()`, with the following failure

```
_tsinfer.LibraryError: Bad path information: time
```

I suspect that's because `add_path()` is checking that stuff is added in time order, but it probably doesn't need to? Perhaps you could take a quick look to confirm. Then I can try perf testing this!!!

### CODE REVIEW

**Comment by hyanwong** [comment]
NB: at the moment I'm saving the ancestor ids for each level in a normal python dict: `{level1:[ancestor_id1, ancestor_id2,..], level1:[ancestor_id3, ancestor_id4,ancestor_id5..], ...}`. But if we have millions of ancestors this might be a bit of a burden, so we could possibly store them e.g. in a zarr array instead, or even re-calculate them on the fly from the intermediate numpy array which I've called `dep_level`.

**Review by jeromekelleher — COMMENTED** [review]
I'd need some time to digest and process this @hyanwong. In the mean time, how about trying stuff out with just the Python engine? This should be easier to understand and see if there's any assumptions about time in there.

**Comment by hyanwong** [comment]
The reason that it's raising an error (e.g. on test_inference.py::TestMetadataRoundTrip::test_from_historical_tree_sequence) is a logic bug (damn), which means that it's possible to get overlapping ancestors that have the same time value, but are at different dependency levels. That means one can become the ancestor of another, but this is disallowed if they have the same time value.

Unless there is a way to restrict LS matching to a subset of the reference panel, which I understand is quite tricky, I think we'll have to solve this by "boosting" overlapping individuals within the same timeslice to the highest dependency level. In the extreme case, with all ancestors at a give time overlapping, this would revert to something like the old scheme. But I don't think we'll be in that situation. Probably worth re-testing with a newer algorithm, though.

**Comment by hyanwong** [comment]
I've added the simple approach mentioned above (where we take all ancestors in the same time slice and set their dependency level to be the maximum of any ancestor in the time slice) and now all tests pass - woohoo. I worry slightly that this will adversely affect the ability to parallelise - I'm just testing it now.

As a follow up, here's a few suggestions for improving the current solution. The problem is not *too* bad because I believe this issue only applies to ancestors that have exactly the same time value (which means that the "dependency level" approach should still be effective in solving the problem of multiple similar ancestor times caused by missing data).

Perhaps the most sophisticated approach is to identify ancestors that are logically independent across positions - i.e. use some sort of interval library to identify groups of ancestors whose joint intervals do not overlap. Within each group, we can then set the dependency level to the maximum in the group. However, I think this will be computationally intensive.

Another approach (which could be combined with the above), would be to allow the *construction* of ancestors to happen at their initially calculated dependency level, but not actually *add* the ancestors to the growing tree sequence until all the ancestors in a given level have been built. For example, each ancestor could have a "dependency level (build)" and a "dependency level (add)". We build the ancestors during their "build" level, but don't add them until their "add" level has been reached. This would, however, involve buffering the ancestors somewhere, so is an additional level of complication.

**Comment by hyanwong** [comment]
Here's the result of the new code on a simulation of 10,000 samples for 10Mb. Looks like it is still working OK. I'm running it on a larger example now - although actually working out the dependencies takes enough time that it seems to be a bit slower in total. I suspect this can be avoided with some more efficient code. It would also be worth trying out on the HGDP (missing data) examples, as I suspect this is where the approach will show major benefits (versus the unbinned ancestors).

Screenshot 2021-03-23 at 12 21 17

**Comment by hyanwong** [comment]
Here's the result from a simulation an order of magnitude larger, with 300,000 sites.

Screenshot 2021-03-23 at 12 55 45

And the result for Wilder's unified dataset, chr20.

Screenshot 2021-03-23 at 14 08 17


The main problem is that finding the dependency levels is slow. I think that can be sped up considerably using an interval library such as https://github.com/biocore-ntnu/ncls, although there are some details to be worked out (e.g. ideally we would gradually build up the interval list as we go down the ancestors, whereas the docs for that library seem to imply that the list is constructed in a single pass.

**Comment by jeromekelleher** [comment]
Thanks @hyanwong. Let's park this here for now. I'll need to get into the weeds on this, and have other things that need finishing up first.

**Comment by hyanwong** [comment]
> Thanks @hyanwong. Let's park this here for now. I'll need to get into the weeds on this, and have other things that need finishing up first.

Yes, I agree. I feel like I've done as much as necessary on this, have shown it works, and identified some issues. That's enough for the moment.

**Comment by benjeffery** [comment]
@hyanwong I've rebased to main, shall I push here or a new PR?
I think there are some quick perf wins here (e.g. not using the `.ancestors` iterator when you only need the times) so I'm just working on those.

**Comment by hyanwong** [comment]
> @hyanwong I've rebased to main, shall I push here or a new PR?

As you like. If a new PR then you're a bit more in control?

> I think there are some quick perf wins here (e.g. not using the `.ancestors` iterator when you only need the times) so I'm just working on those.

Good point, thanks. I didn't try to optimise this in any way, so not surprised there are several wins.

**Comment by hyanwong** [comment]
Improved by @benjeffery 's reworking, so no longer relevant.

**Pull request closed without merging**
