### PR TITLE
Fix zarr issue with 2.11

### PR DESCRIPTION
**Pull request by jeromekelleher**
Closes issue #628

### CODE REVIEW

**Comment by benjeffery** [comment]
Hmm, I'm thinking these are related. Guessing that 2D arrays are being filled with the second dimension being zero.

**Comment by jeromekelleher** [comment]
I've had a go at it as well and it's quite messy. Definitely agree the remaining failures are related.

**Comment by benjeffery** [comment]
So I think I have fixed all the zarr issues - however the doc build is now failing.

**Comment by jeromekelleher** [comment]
Messy... Let's give Zarr a few more days to see if these bugs will be fixed and make a descision on whether we want these workarounds or not.

**Comment by benjeffery** [comment]
Closing this PR as we are pinning for now.

**Pull request closed without merging**
