### PR TITLE
Switch to pytest

### LINKED ISSUE #351: Update to use pytests
After discussion with @benjeffery - it would be good to update tsinfer to the same as tskit. Also, Perhaps we should switch to Github Actions for testing, as we did for tskit

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #351

### CODE REVIEW

**Comment by hyanwong** [comment]
Yay, thanks @benjeffery. Do I need to do anything to help with this?

**Comment by benjeffery** [comment]
> Yay, thanks @benjeffery. Do I need to do anything to help with this? NB Fixes #351

Nope, it's in progress! Will finish on Monday.

**Comment by hyanwong** [comment]
> > Yay, thanks @benjeffery. Do I need to do anything to help with this? NB Fixes #351
> 
> Nope, it's in progress! Will finish on Monday.

Great. No hurry. Thanks for seeing to this, BTW. You're being kept very busy, I must say.

**Comment by benjeffery** [comment]
> You're being kept very busy, I must say.

Don't tell anyone, but most of this was outsource to a robot! 🤖

**Comment by hyanwong** [comment]
> Don't tell anyone, but most of this was outsource to a robot! 🤖

It's the start of the singularity.

**Comment by benjeffery** [comment]
All good to go.

**Comment by hyanwong** [comment]
Yay. Merge it, quick, before we start writing more unit tests :)

**Review by jeromekelleher — APPROVED** [review]
Fantastic, thanks @benjeffery!

**Comment by benjeffery** [comment]
I'll rebase as this needs a manual merge.

**Pull request merged**
