### PR TITLE
Build and deploy wheels

### PR DESCRIPTION
**Pull request by benjeffery**
I've omitted Python 3.9 on OSX for now.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks!

**Comment by benjeffery** [comment]
> LGTM, thanks!
BTW I don't have the PyPI permissions to generate an api key that we'll need before release for this to work.

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by jeromekelleher** [comment]
> BTW I don't have the PyPI permissions to generate an api key that we'll need before release for this to work.

Should have this now.

**Comment by benjeffery** [comment]
> > BTW I don't have the PyPI permissions to generate an api key that we'll need before release for this to work.
> 
> Should have this now.

Sorry - not seeing this on my account yet.

**Comment by jeromekelleher** [comment]
Says there's an invite pending, maybe takes a while for the invite to get to you? (Also for tszip)

**Comment by benjeffery** [comment]
Got it! API key added to secrets in github.

**Pull request merged**
