### PR TITLE
Rework sgkit ancestral allele 

### LINKED ISSUE #847: Hard error on missing sgkit ancestral state
Currently, we raise a warning on missing ancestral state. I think this should be a hard error as the warning is easily missed and the resulting tree sequence will be pretty much garbage. The use of the zeroth allele is a legacy hangover from early tsinfer days - if the user really wants to do that they can specify and ancestral state array which contains the zeroth allele for each site.

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #847, #846

### CODE REVIEW

**Comment by benjeffery** [comment]
Trying to fix this odd `TypeError: Could not convert smc_primesmc_prime to numeric` error here.

**Comment by jeromekelleher** [comment]
Worth a separate PR to bring in pandas changes?

**Comment by benjeffery** [comment]
Some windows failure, which I'll probably skip, but this is worth a review now.

**Review by jeromekelleher — APPROVED** [review]

**Comment by benjeffery** [comment]
Looks like re-pushing with a new commit hash has awoken circleCI from its slumber.

**Pull request merged**
