### PR TITLE
Remove zarr workarounds and update zarr

### LINKED ISSUE #656: Pick up Zarr 2.11.2
zarr-developers/zarr-python#1002

Should help with some workarounds we had to make. @benjeffery you're closest to this one, mind picking it up?

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #656

### CODE REVIEW

**Comment by benjeffery** [comment]
Hasn't yet hit conda - will check back later.

**Comment by benjeffery** [comment]
This will now need to be 2.11.3 as the fix in 2.11.2 was not complete: https://github.com/zarr-developers/zarr-python/pull/1001#issuecomment-1090155352

**Comment by jeromekelleher** [comment]
Conda packages up now I think, but see note about needing 2.11.3

**Comment by benjeffery** [comment]
@jeromekelleher All seems to work here now.

**Review by jeromekelleher — APPROVED** [review]
Nice, thanks @benjeffery 

Should we follow up with a quick point release to update the packaging now that the dust has settled on bad Zarr versions?

**Pull request merged**
