### PR TITLE
Test suite to use new msprime calling convention

### PR DESCRIPTION
**Pull request by hyanwong**
Ideally we should switch to the new msprime for testing, since it has discrete genome coords, individuals, metadata, etc. This switches the tree sequences used for testing to new format versions

### CODE REVIEW

**Comment by hyanwong** [comment]
Oh damn, requires tskit 0.4. Will wait, I guess.

**Comment by hyanwong** [comment]
Lots of this seems to be "TypeError: 'PopulationTable' object does not support item assignment". Is this post-tskit 0.4.0?

**Comment by hyanwong** [comment]
I think this is entirely uncontroversial, and gets CI working again, so other PRs can start going through. Looks like the requirements conflict needs a tiny tweak before merging, so that we are using tskit 0.4.1, but after that it presumably can be merged. Do you think you might have time to do that @benjeffery or @jeromekelleher ? I'm not sure how to do it.

**Comment by jeromekelleher** [comment]
I'll take a look now.

**Comment by hyanwong** [comment]
Thanks Jerome. That's much appreciated.

**Review by jeromekelleher — APPROVED** [review]
That should do it, thanks for sorting this out @hyanwong!

**Comment by hyanwong** [comment]
Hooray, thanks @jeromekelleher. Merge away

**Comment by jeromekelleher** [comment]
Looks like a random number problem on Windows, can you take a look please?

**Pull request merged**
