### PR TITLE
Do not include missing allele in tree seq builder num_alleles

### LINKED ISSUE #406: Add "exclude_missing" to num_alleles() method?
It strikes me that when we use `num_alleles` in the algorithm, we should probably not be counting `-1` as an allele, e.g. here:https://github.com/tskit-dev/tsinfer/blob/7f69d59b37217146b700364fa2de0da4fefc56c8/tsinfer/algorithm.py#L736

I wonder if we should be populating the tree sequence builder `num_alleles` array with the number without missing data? It seems odd that the HMM probabilities might depend on whether we allowed an extra allele type for missing data or not.

If I'm right (not 100% sure yet) then perhaps the num_alleles method could have an extra param (e.g. "exclude_missing", default false, so that previous behaviour is maintained) https://github.com/tskit-dev/tsinfer/blob/7f69d59b37217146b700364fa2de0da4fefc56c8/tsinfer/formats.py#L1898

And we would set `exclude_missing=True` here:
https://github.com/tskit-dev/tsinfer/blob/7f69d59b37217146b700364fa2de0da4fefc56c8/tsinfer/inference.py#L931

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #406 and addresses https://github.com/tskit-dev/tsinfer/issues/403#issuecomment-741846467 about counting missing data as an allele.

I'm slightly tempted to default to "count_missing=False", but this would not be backward compatible. OTOH, I'm not sure the missing data stuff has been previously released anyway. What do you think @jeromekelleher ?

### CODE REVIEW

**Comment by hyanwong** [comment]
FWIW, the tests pass if we default to `count_missing=False' too.

**Comment by jeromekelleher** [comment]
Looks good, but why would we want to count the missing data as an allele? I think it's just a bug and the parameter isn't needed. There's nothing to be compatible with, this is all unreleased.

**Comment by hyanwong** [comment]
Good point. Parameter removed. Now if `None` is last in the allele list we don't count it as an allele. I guess that precludes people from adding "None" as true allele type, which is probably fine anyway.

**Comment by jeromekelleher** [comment]
It's what we do [here](https://github.com/tskit-dev/tsinfer/blob/main/tsinfer/inference.py#L785) already anyway. Which is why I think our existing analyses should be fine?

**Comment by hyanwong** [comment]
Yep - just merge it I think.

**Review by jeromekelleher — APPROVED** [review]

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Pull request merged**
