### PR TITLE
Allow provenance tests to pass again

### PR DESCRIPTION
**Pull request by hyanwong**
(by removing the provenance added during simplifying in extract-ancestors)

### CODE REVIEW

**Comment by hyanwong** [comment]
I think the underlying tskit library started saving an extra provenance on `simplify`, which broke a few tests.

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by jeromekelleher** [comment]
Any idea why mergify isn't merging this @benjeffery?

**Comment by benjeffery** [comment]
> Any idea why mergify isn't merging this @benjeffery?

https://github.com/tskit-dev/tsinfer/pull/345

**Comment by benjeffery** [comment]
@mergifyio refresh

**Comment by benjeffery** [comment]
@mergifyio rebase

**Pull request merged**
