### PR TITLE
Test and build wheels on 3.10

### LINKED ISSUE #627: Add 3.10 to tests.
As conda is already trying to packaging this for 3.10 we need to update tests.
https://github.com/conda-forge/tsinfer-feedstock/pull/1

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #627

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks like we have a problem with conda/numpy/msprime for 3.10. Do we need to rebuild the conda package for msprime 3.10 or something?

**Comment by benjeffery** [comment]
@jeromekelleher This is done. Wow. Pandas has ruined my evening. There isn't a version that you can install on both 3.7 and 3.10. Plus the API now doesn't support `norm` in plotting.

**Review by jeromekelleher — APPROVED** [review]
Eesh, thanks for picking through this mess @benjeffery!

**Comment by benjeffery** [comment]
Manual merge for mergify config.

**Pull request merged**
