### PR TITLE
Extend greedy mutation coalescing

### PR DESCRIPTION
**Pull request by jeromekelleher**
WIP

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This seems to be working well in practise now, so ready to merge. It's pretty clear that ultimately this code doesn't belong in tsinfer  and will be moved out into the dedicated package sc2ts when we get the required infrastructure in tskit (although we really should be doing something like this with path-compression, which currently doesn't reason about mutations at all).

@hyanwong - would you like to take a look through or shall I merge?

**Comment by hyanwong** [comment]
I'm happy to look through if you want extra eyes, but also happy for you to merge if you need it right now.

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Comment by jeromekelleher** [comment]
I think we'll just merge, seems to be working well and I'd like to have a stable git hash to point at in provenance.

**Pull request merged**
