### PR TITLE
Add note about validity of node times & tsdate

### PR DESCRIPTION
**Pull request by hyanwong**

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM. We should probably put something similar in the GitHub README too so it's unmissable.

**Comment by hyanwong** [comment]
> LGTM. We should probably put something similar in the GitHub README too so it's unmissable.

Shall I add this to this PR? Also I see there's a README.rst which I assume is obsolete - I could remove that at the same time?

**Comment by jeromekelleher** [comment]
Please do. I'd leave README.rst alone though, I'm sure this is involved in the Python packaging (it's the front page on PyPI AFAIK)

**Comment by hyanwong** [comment]
> Please do. I'd leave README.rst alone though, I'm sure this is involved in the Python packaging (it's the front page on PyPI AFAIK)

Ah, I didn't realise that. Probably worth putting a comment in the rst file to that effect?

**Pull request merged**
