### PR TITLE
Fix OSX CI failures

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Comment by benjeffery** [comment]
Installing deps hung for 1h30... trying again.

**Comment by benjeffery** [comment]
@jeromekelleher should be good to go.

**Review by jeromekelleher — APPROVED** [review]

**Comment by benjeffery** [comment]
Conda is hanging for hours, even with a retry. Will try resetting the cache.

**Comment by benjeffery** [comment]
Still hanging here on ubuntu - will try switching to mamba

**Comment by benjeffery** [comment]
I think that has done the trick. No idea why it suddenly started hanging!

**Pull request merged**
