### PR TITLE
Add support for multiple mutations

### PR DESCRIPTION
**Pull request by jeromekelleher**
I fixed the initial issue causing #647, but it's after opening up another can of worms with the evaluations.

Looks like we should just try to limit ourselves to two alleles when using tsinfer? @hyanwong, do you remember where this was at?

### CODE REVIEW

**Comment by hyanwong** [comment]
When there are >2 alleles we simply place the mutations using parsimony, and don't use them for inference. So normally, it's fine using triallelic alleles.

We should advise people that if they really need to use them for inference, they *can* use tri- and tetra-allelic sites by picking some of the alleles and setting the samples that have those alleles to "missing data", leaving samples with only 2 allelic states. I guess in general you want to chose the ancestral state then the next most frequent allele as the two to keep.

I'm unsure as to why @szhan was having problems with triallelic sites. Perhaps because he was porting them directly into the ancestors TS, rather than allowing the `match_ancestors` routine to mark those sites as not-for-inference?

**Comment by hyanwong** [comment]
> I'm unsure as to why @szhan was having problems with triallelic sites in https://github.com/tskit-dev/tsinfer/issues/647

Ah, he was using `make_ancestors_ts`. So that (undocumented) function simply needs to omit the non-biallelic sites. So perhaps we should change the name of this issue to "make_ancestors_ts should omit non-biallelic sites", @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Ah yes, that was it, thanks @hyanwong. Updated to remove all sites that either are singletons or have more than one mutation. Should be good to merge now and ready to use for @szhan 's application.

**Comment by jeromekelleher** [comment]
Ah yes, that was it, thanks @hyanwong. Updated to remove all sites that either are singletons or have more than one mutation. Should be good to merge now and ready to use for @szhan 's application.

**Comment by jeromekelleher** [comment]
Going to merge this so Shing can make progress, I think it's pretty uncontroversial.

**Comment by jeromekelleher** [comment]
Going to merge this so Shing can make progress, I think it's pretty uncontroversial.

**Pull request merged**
