### PR TITLE
Change "age" references to "time"

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes https://github.com/tskit-dev/tsinfer/issues/149

This also changes the underlying storage name from `sites/age` to `sites/time`, and the name of the equivalent parameter in `SampleData.add_site()`, so it will break code if anyone is specifying the "age" parameter by name not position. But I think @awohns is the only user of this functionality at the moment.

If we want `tsinfer` to be terminologically consistent with `tskit` like this, then this is the time to do it!

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good thanks, we definitely want to do this. Before we merge we need to

a) Bump the file format major version number(s), as this is a breaking change (old code will no longer be able to read these files, and we'll no longer be able to read old files.). We should open an issue tracking whether we want to add an 'upgrade' function to bring old .samples files up to date.

b) Pad out the test coverage if the missing stuff is Python (don't worry if it's C).

**Comment by hyanwong** [comment]
> a) Bump the file format major version number(s), as this is a breaking change (old code will no longer be able to read these files, and we'll no longer be able to read old files.). 

I don't know where this is stored. Would it be OK for you to do this - much quicker I guess.

> We should open an issue tracking whether we want to add an 'upgrade' function to bring old .samples files up to date.

We have https://github.com/tskit-dev/tsinfer/issues/144 - can we use that?

> b) Pad out the test coverage if the missing stuff is Python (don't worry if it's C).

The main coverage seems to be no tests of the `print_state` functions used for debugging. I'm about to stick in a few tests that simply call them and check they don't bomb out. No point in doing anything more detailed, as I'm guessing the output will change as we find other issues to debug.

**Comment by jeromekelleher** [comment]
> I don't know where this is stored. Would it be OK for you to do this - much quicker I guess.

It's in the formats.py file somewhere. Should be easy enough to track down? I'm not going to be working on this for another week or two.

> We have #144 - can we use that?

Yep, that's good.

> The main coverage seems to be no tests of the print_state functions used for debugging. I'm about to stick in a few tests that simply call them and check they don't bomb out. No point in doing anything more detailed, as I'm guessing the output will change as we find other issues to debug.

Sounds good.

**Comment by hyanwong** [comment]
> > I don't know where this is stored. Would it be OK for you to do this - much quicker I guess.
> 
> It's in the formats.py file somewhere. Should be easy enough to track down? I'm not going to be working on this for another week or two.

Do you mean [this](https://github.com/tskit-dev/tsinfer/blob/919174ca5716663308d4f9ab75393d6b83e0d40f/tsinfer/formats.py#L704) - if so should I change it to `(2, 1)` or `(3, 0)`?

**Comment by jeromekelleher** [comment]
> Do you mean this - if so should I change it to (2, 1) or (3, 0)?

Yes, that's it. (We should start a Changelog also to log all these breaking changes in case we forget)

**Comment by hyanwong** [comment]
Format bumped, and changelog written. I wonder, however, if we should wait to include https://github.com/tskit-dev/tsinfer/issues/188 before merging (if we agree that it is a good idea), as I guess changing from `uint8` to `bool` for sites_inference might mean a change in the underlying zarr storage format?

**Comment by hyanwong** [comment]
Actually, I think we should also pick off the commit that changes the allele type from unsigned to signed (https://github.com/hyanwong/tsinfer/commit/6900f51faa19bb3f1c8d1aa87b25dcf104c96d30) and incorporate this too, as that will also create a breaking change. Then we make all the breaking changes at once, and incorporate into format 3.0. Shall I make a separate PR for the uint->int change @jeromekelleher ?

**Comment by hyanwong** [comment]
Just rebased and this is now ready to merge, which should bump us to tsinfer file versions 3.0. It may be worth releasing tsinfer v0.1.5 as a result of these changes. @jeromekelleher ?

**Comment by jeromekelleher** [comment]
LGTM, thanks @hyanwong, will merge once CI is done.

Re releasing, I think we should provide an upgrade path for old files (#144)  before we do this. It'll be hella painful to have to reprocess all the UKB files (e.g.), and the upgrade should be easy to do.

**Comment by hyanwong** [comment]
Good point about the upgrade path. I'm not sure how to do this, and don't really want to take it on, however.

**Comment by jeromekelleher** [comment]
Probably makes more sense to wait on the 0.2.0 release https://github.com/tskit-dev/tsinfer/milestone/1 I think --- we've already enough changes for a major version, so we'd be better to bundle them all together.

**Pull request merged**
