### PR TITLE
update CHANGELOG

### PR DESCRIPTION
**Pull request by awohns**
Notes #492 and #467 in the CHANGELOG

### CODE REVIEW

**Review by benjeffery — COMMENTED** [review]
Great, thanks!

Just needs a mention of Python 3.7 as a new requirement and it is good to go.

**Comment by awohns** [comment]
I'll just add the issues and user attributions too

**Comment by benjeffery** [comment]
I'll merge this after I fix the CI issue

**Comment by benjeffery** [comment]
@mergify rebase

**Review by benjeffery — APPROVED** [review]

**Pull request merged**
