### PR TITLE
Check for duplicate alleles

### LINKED ISSUE #927: Check all alleles at a site are unique before inference
I'm finding that tsinfer isn't correctly inferring the genotypes for Sgkit files in the trivial instance below. This seems pretty worrying. What do I have wrong?

```python
import sgkit as sg
import tsinfer

ds = sg.simulate_genotype_call_dataset(n_variant=10, n_sample=4, missing_pct=0, phased=True, seed=1)
ds['variant_allele'] = ds['variant_allele'].astype(str) # hack around https://github.com/tskit-dev/tsinfer/issues/810
ds.update({'variant_ancestral_allele': ds['variant_allele'][:,0]})
ds.to_zarr('/tmp/ds.zarr', mode='w')
sd = tsinfer.SgkitSampleData('/tmp/ds.zarr')
ts = tsinfer.infer(sd)
print("Inferred_genos    Zarr_genotypes    SampleData_genos  Ts alleles")
for v, sgv, sdv in zip(ts.variants(), ds.call_genotype, sd.sites_genotypes):
    bad = "<<<< BAD!!!" if not (v.genotypes == sdv).all() else ""
    print(v.genotypes, sgv.values.flatten(), sdv, v.alleles, bad)
```

Shows that the 7th and 8th site are incorrect:

```
Inferred_genos    Zarr_genotypes    SampleData_genos  Ts alleles
[1 0 1 0 1 0 1 1] [1 0 1 0 1 0 1 1] [1 0 1 0 1 0 1 1] ('G', 'C') 
[0 1 1 0 0 0 0 0] [0 1 1 0 0 0 0 0] [0 1 1 0 0 0 0 0] ('G', 'A') 
[1 0 1 0 1 1 0 0] [1 0 1 0 1 1 0 0] [1 0 1 0 1 1 0 0] ('T', 'A') 
[1 0 1 1 1 0 1 1] [1 0 1 1 1 0 1 1] [1 0 1 1 1 0 1 1] ('G', 'A') 
[1 1 1 1 0 1 0 0] [1 1 1 1 0 1 0 0] [1 1 1 1 0 1 0 0] ('C', 'G') 
[0 0 1 1 1 0 0 1] [0 0 1 1 1 0 0 1] [0 0 1 1 1 0 0 1] ('G', 'A') 
[0 0 0 0 0 0 0 0] [0 1 0 1 1 0 0 1] [0 1 0 1 1 0 0 1] ('T',) <<<< BAD!!!
[0 0 0 0 0 0 0 0] [1 0 0 0 0 1 0 1] [1 0 0 0 0 1 0 1] ('C',) <<<< BAD!!!
[0 1 0 1 1 1 1 1] [0 1 0 1 1 1 1 1] [0 1 0 1 1 1 1 1] ('T', 'G') 
[0 0 1 1 0 1 1 0] [0 0 1 1 0 1 1 0] [0 0 1 1 0 1 1 0] ('A', 'G') 
```

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #927.

I assume we are happy to take the hit of looping through all the sites and doing a `set()`. An alternative would be to do an `np.unique` by row, but then we would need to remove the duplicate `""` entries.

### CODE REVIEW

**Comment by hyanwong** [comment]
I'll test. Meanwhile, I messed up the GH commits with another PR, so will fix and force push

**Comment by benjeffery** [comment]
LGTM - I don't think the loop through the alleles will be that expensive for most cases - unless lots of sites have hundreds of alleles.

This has made me realise the vcfzarr spec should probably be more explicit that zero-length alleles are not allowed. It is currently there as implicit as it states `""` is a fill value.

**Comment by hyanwong** [comment]
> This has made me realise the vcfzarr spec should probably be more explicit that zero-length alleles are not allowed. It is currently there as implicit as it states "" is a fill value.

Zero-length alleles are not allowed in VCF files, so I guess that's implicit too. However, we might want to allow representation of indels internally like that, otherwise there are forms of genetic variation that can be represented in a VCF that can't be represented in the tsinfer input (see https://github.com/tskit-dev/tsinfer/issues/893#issuecomment-1923359429)

**Comment by hyanwong** [comment]
Rolled into #963 as part of review, and tested with a large file.

**Pull request closed without merging**
