### PR TITLE
Place provenance recording in top level functions

### PR DESCRIPTION
**Pull request by hyanwong**
Like the other functions in Tskit, I think we should set provenance in the top level functions such as tsinfer.infer, or tsinfer.match_ancestors. This pulls out the provenance stuff from within lower level functions and puts it in the top functions. Hopefully this will make it easier to include more parameters etc in the provenance.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Do we have an application for this? I feel like a lot more time has been spent on provenance that has actually been gained. Unless there's an immediate problem we're trying to solve I'd rather just leave it alone.

**Comment by hyanwong** [comment]
It would be pretty useful to me (and presumably others) to be able to know from the tree sequence the mismatch rates and recombination rates used for inference. That's the main thing in my book, and I'm assuming it would be pretty easy to add those to the provenance.

**Comment by jeromekelleher** [comment]
And they are not being recorded in the lower levels?

**Comment by hyanwong** [comment]
No, there's no way to get them back out of the tree sequence, AFAIK.

**Comment by hyanwong** [comment]
Agreed. I would like to keep it active for after 0.3.0 though.

**Comment by hyanwong** [comment]
I've revised my opinion on this @jeromekelleher - I don't think this is controversial, is it? We aren't recording anything more in the provenances here, simply doing what we do in tskit. It confused me for a while when looking at the CLI injected provenances that all the match_ancestor etc stuff was in there too, so a way to take it out (assuming we want to do that) when calling via the CLI would be helpful, I think.

**Review by jeromekelleher — APPROVED** [review]
I see, yes, this is helpful.

**Pull request merged**
