### PR TITLE
Update ancestors alg

### PR DESCRIPTION
**Pull request by jeromekelleher**
Not to be merged --- just making branch available for use.

### CODE REVIEW

**Comment by hyanwong** [comment]
Is this latest commit (00ebf1d) ready for testing?

**Comment by jeromekelleher** [comment]
Yes please! This version will only remove a sample from S if it disagrees with the consensus for two sites in a row. Hopefully this will make it more robust to error...

FYI, I ended up making a couple of other changes:
1. For short-term convenience, all ancestors now are only for a single focal site. I'm not convinced that having multiple focal sites did much at scale, or that the way we were bundling them together made sense. In any case, path-compression should pick up the patterns that result when we split up an ancestor that is really composed of multiple focal sites. I can change this back to the way it was if we think it'll make a difference (and the current code isn't good enough).

2. In the previous algorithm we always had a trailing set of 0s after the site we computed an ancestral state for, up to the site at which we decided to break. Now, the ancestor stops at the last site that we computed an ancestral state. I hadn't really thought this through before, but I think the current approach is probably the right way to do it. Easy to change though if this turns out not to be the case.

**Comment by hyanwong** [comment]
Testing now. FWIW I would be inclined to leave the trailing zeros you mention in (2): the true break could be anywhere up to the non-matching site. By breaking earlier, we may risk forcing breaks into positions adjacent to the last non-matching site, rather than getting the matching algorithm to locate the most likely (more generally, I would be inclined towards longer ancestors rather than shorter ones, if allowed by performance issues)

**Comment by hyanwong** [comment]
Disappointingly, the subsampling results for 00ebf1d seem to be worse than the previous iteration, at least for small sample sizes (I'm labelling this c8f3abf but in the list above it seems to be 1add28f). For example, for a 1Mb length with no error, the KC metric now hovers around 2.275 (or 2.325 if polytomies broken), whereas before it was around 2.175 (2.220). With error, we are no longer getting an increasing distance with increasing sample size, but that's because we are starting off worse.


[00ebf1d-metrics_subsampling.pdf](https://github.com/tskit-dev/tsinfer/files/2220743/00ebf1d-metrics_subsampling.pdf)
[c8f3abf-metrics_subsampling.pdf](https://github.com/tskit-dev/tsinfer/files/2220744/c8f3abf-metrics_subsampling.pdf)

**Comment by hyanwong** [comment]
Can we possibly switch the previous behaviour under (2) (leave the trailing zeros in) if it's easy to do so, and I can try running again, to see if this is the root of the problem?

**Comment by jeromekelleher** [comment]
OK, let's see what the rest of the results say. I can swap back in the trailing zeros easily tomorrow if you want to try that out.

**Comment by hyanwong** [comment]
Just got the other results in (metrics_all_tools_accuracy). Also now slightly worse than c8f3abf, even with error. I guess the easiest thing is to swap trailing zeros in, and it will be slightly more difficult to go back to multiple focal sites?

**Comment by jeromekelleher** [comment]
> Just got the other results in (metrics_all_tools_accuracy). 00ebf1d is also now slightly worse than c8f3abf, even with error. I guess to test why this might be, the easiest thing is to swap trailing zeros in, and it will be slightly more difficult to go back to multiple focal sites?

Interesting... Yes, I'll swap back in the trailing zeros first.

**Comment by hyanwong** [comment]
Two plots attached, if you want to check - easiest to flip between them to look at the differences.

[00ebf1d-metrics_all_tools_accuracy.pdf](https://github.com/tskit-dev/tsinfer/files/2222417/00ebf1d-metrics_all_tools_accuracy.pdf)
[c8f3abf-metrics_all_tools_accuracy.pdf](https://github.com/tskit-dev/tsinfer/files/2222419/c8f3abf-metrics_all_tools_accuracy.pdf)

**Comment by jeromekelleher** [comment]
I've updated this @hyanwong --- we now pad the ancestors out with trailing zeros up to (and including) the  older site at which we failed. I set the value of the site where we break to 0 basically because it's more convenient. An argument could be made either way. Let's see how it goes...

**Comment by hyanwong** [comment]
Just for the record, I should point out here that reinstating the trailing zeros (g169c3cc) reinstated the older (desirable) accuracy measures with increasing mutation rate, as seen in c8f3abf. However, it doesn't seem to have quite reinstated the previous accuracy-with-subsampling behaviour, which, for the no-error case, is still a little worse in absolute KC values in g169c3cc compared to c8f3abf. The pattern for the with-error case in g169c3cc is a little more desirable, however.

I've uploaded the plots that show this in this commit https://github.com/mcveanlab/treeseq-inference/commit/92df915a3c963dd62d9d2887dd7e1cebcee19c65. The performance on the GDF5 dataset is also not entirely restored (see the origsize10_with_poly / filtered case below). This implies to me that the "ancestors now only for a single focal site" change might not be doing quite what we expect. But this may only apply to small sample sizes.

```
#revision c8f3abf (less draconian stopping rule than MASTER)
                       filtered     full  allsnps
origsize10_with_poly   7.000000 7.615773 9.949874
subsamp6k_with_poly    7.071068 7.483315 9.643651


#revision 00ebf1d (less draconian stopping rule, allow for some error, no trailing zeros)
                       filtered     full   allsnps
origsize10_with_poly   7.549834 7.745967 10.000000
subsamp6k_with_poly    7.280110 6.855655  9.539392

#revision g169c3cc (less draconian stopping rule, allow for some error, trailing zeros)
                       filtered     full   allsnps
origsize10_with_poly   7.549834 7.745967 10.000000
subsamp6k_with_poly    7.280110 6.855655  9.643651
```

**Comment by jeromekelleher** [comment]
Since we're moving in the right direction in terms of large scale real data with this, I'm going to merge this. We're clearly not done in terms of ancestor generation, but it's worthwhile keeping this current algorithm in the history for future reference.

**Pull request merged**
