### PR TITLE
Allow non-biallelic alleles to be input and mapped

### PR DESCRIPTION
**Pull request by hyanwong**
This simply marks them as not for inference, and uses the map_mutations method to place the mutations so as to re-create the correct haplotypes

### CODE REVIEW

**Comment by hyanwong** [comment]
Closing and reopening because of a temporary appveyor glitch

**Comment by hyanwong** [comment]
This is ready for review. There is only one added test, but that might be considered enough?

**Comment by jeromekelleher** [comment]
Very nice, but could use a bit more testing. What are the limits here, i.e. what happens if there's lots of alleles? There must be some other corner cases that need exploring.

**Comment by hyanwong** [comment]
Yep, as well as the limit of large numbers of alleles, we should also check interaction with `from_tree_sequence` (c.f. #211) I suspect. Ping other suggestions in this thread and I can try to implement something.

Note, however, that since we are simply applying `map_mutations`, I would hope that some of the cases such as large allele numbers would be mostly checked in the tests for that method.

**Comment by jeromekelleher** [comment]
> Note, however, that since we are simply applying map_mutations, I would hope that some of the cases such as large allele numbers would be mostly checked in the tests for that method.

Sure, it's just good to locally characterise the behaviour so we don't run into suprises later.

**Comment by hyanwong** [comment]
I've added a test for 64 alleles (passes) and 65 alleles (expected to fail because `map_mutations()` only allows 64 alleles), a test if we only have a subset of the alleles indexes in `genotypes`, and also a test that `from_tree_sequence()` works where we have multiple mutations at a site. Happy to add other suggestions, otherwise this can probably be merged.

**Comment by jeromekelleher** [comment]
This is excellent, merging.

**Pull request merged**
